### ISSUE TITLE
Task: Update use of headers

### ISSUE THREAD

**Issue by MLCochrane** [MLCochrane/gosyp#161]
# Task
As described in #134 the use of headers is poor as it was never brought out of a prototype phase. This means there's no reasonable header order, and there's no header in places where it would be helpful to have them.

# Subtasks
- [x] add main title bar for h1
- [x] add headers to sidebar
- [x] convert room info items to headers
- [ ] remove header usage in any typography that's using it for style purposes only
