### ISSUE TITLE
Task: Implement e2e tests in CI with puppeteer, jest

### ISSUE THREAD

**Issue by MLCochrane** [MLCochrane/gosyp#165]
# Task
This task encompasses work for setting up the e2e test suite running in CircleCI. Additional context in #155 

# Subtasks
- [ ] Expand CircleCI config to run docker compose with our site containers and a puppeteer/jest container
- [ ] Test suite for frontend forms, main room lifecycle
- [ ] Test suite for main chat, communication and updating room details
